// This is a JavaScript data file, not JSON.
// It allows us to load it easily in the browser.
const reportData = {
    vehicle: "YEAR MAKE MODEL - VIN",
    items: [
        // --- 1. Initial Documentation & Overview ---
        { category: "Initial Documentation & Overview", name: "VIN Verification (Multiple Locations)", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Odometer Reading Documented", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Warning Light Check", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Title/Registration Check", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Recall Check (Online)", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Service History Review", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Obvious Exterior Damage", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Obvious Interior Damage", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Signs of Major Modifications", status: "good", notes: "", photoUrl: "" },
        { category: "Initial Documentation & Overview", name: "Initial Condition Photos", status: "good", notes: "", photoUrl: "" },

        // --- 2.1 Driver's Side A-Pillar / Fender / Mirror ---
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "VIN Match (A-Pillar/Dash)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Fender: Paint Condition/Match", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Fender: Dents/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Fender: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Mirror: Glass Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Mirror: Housing Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Mirror: Power Function (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Mirror: Signal (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "A-Pillar Trim", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Door Top Seal", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver's A-Pillar/Fender/Mirror", name: "Windshield Edge", status: "good", notes: "", photoUrl: "" },

        // --- 2.2 Front Driver's Quarter ---
        { category: "Exterior: Front Driver's Quarter", name: "Wheel: Condition (Scratches, Bends)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Wheel: Lug Nuts/Bolts", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Brand/Model Match", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Size Match (Plaquard)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Tread Depth (Inner/Mid/Outer)", status: "good", notes: "Measure: I__ M__ O__ mm", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Age (DOT Code)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Condition (Cracks, Bulges)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Pressure (Check/Adjust)", status: "good", notes: "PSI: __", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Tire: Wear Pattern", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Brake Rotor: Surface", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Brake Rotor: Thickness (Visual Est.)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Brake Pads: Thickness (Visual Est.)", status: "good", notes: "Approx __ mm", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Brake Caliper: Leaks/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Brake Line/Hose: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Suspension: Strut/Shock Leak", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Suspension: Bushing Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Suspension: Ball Joint Play (Visual)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "CV Axle Boot (if FWD/AWD)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Headlight: Lens Clarity", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Headlight: Housing/Seal", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Headlight: Operation (Low/High/Signal)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Fog Light: Condition/Op (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Bumper Corner: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Bumper Corner: Damage/Scuffs", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Bumper Corner: Sensors (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Wheel Well Liner", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Brake Temp Baseline (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Exterior: Front Driver's Quarter", name: "Wheel Bearing Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },

        // --- 2.3 Front End ---
        { category: "Exterior: Front End", name: "Hood Latch Mechanism", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Grille: Condition/Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Front Trim: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Front Bumper: Center Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Front Bumper: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Front Bumper: Impact Absorber Area", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "License Plate Mount", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Front Sensors/Cameras (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Signs of Front Impact Damage", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Hood Alignment (Front Edge)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Front Emblem Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front End", name: "Windshield Washer Jets", status: "good", notes: "", photoUrl: "" },

        // --- 2.4 Front Passenger Quarter ---
        { category: "Exterior: Front Passenger Quarter", name: "Wheel: Condition (Scratches, Bends)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Wheel: Lug Nuts/Bolts", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Brand/Model Match", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Size Match (Plaquard)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Tread Depth (Inner/Mid/Outer)", status: "good", notes: "Measure: I__ M__ O__ mm", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Age (DOT Code)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Condition (Cracks, Bulges)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Pressure (Check/Adjust)", status: "good", notes: "PSI: __", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Tire: Wear Pattern", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Brake Rotor: Surface", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Brake Rotor: Thickness (Visual Est.)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Brake Pads: Thickness (Visual Est.)", status: "good", notes: "Approx __ mm", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Brake Caliper: Leaks/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Brake Line/Hose: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Suspension: Strut/Shock Leak", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Suspension: Bushing Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Suspension: Ball Joint Play (Visual)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "CV Axle Boot (if FWD/AWD)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Headlight: Lens Clarity", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Headlight: Housing/Seal", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Headlight: Operation (Low/High/Signal)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Fog Light: Condition/Op (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Bumper Corner: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Bumper Corner: Damage/Scuffs", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Bumper Corner: Sensors (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Fender: Alignment/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Hood Alignment at Corner", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Wheel Well Liner", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Brake Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Exterior: Front Passenger Quarter", name: "Wheel Bearing Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },

        // --- 2.5 Passenger Side ---
        { category: "Exterior: Passenger Side", name: "Passenger Mirror: Glass Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Mirror: Housing/Functions", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Door Operation (Front/Rear) Handles/Locks", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Front Door: Panel Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Front Door: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Front Door: Window Trim", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Front Door: Weatherstripping", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Rear Door: Panel Alignment (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Rear Door: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Rear Door: Window Trim", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Rear Door: Weatherstripping", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Rocker Panel/Side Skirt: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Rocker Panel/Side Skirt: Damage/Corrosion", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Side Glass: Condition (Chips, Scratches)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "Side Trim Pieces: Secure", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Passenger Side", name: "B-Pillar Trim (if applicable)", status: "good", notes: "", photoUrl: "" },

        // --- 2.6 Rear Passenger Quarter ---
        { category: "Exterior: Rear Passenger Quarter", name: "Quarter Panel: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Quarter Panel: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Wheel Well Liner", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Wheel: Condition (Scratches, Bends)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Wheel: Lug Nuts/Bolts", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Brand/Model Match", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Size Match (Plaquard)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Tread Depth (Inner/Mid/Outer)", status: "good", notes: "Measure: I__ M__ O__ mm", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Age (DOT Code)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Condition (Cracks, Bulges)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Pressure (Check/Adjust)", status: "good", notes: "PSI: __", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Tire: Wear Pattern", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Brake Rotor: Surface", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Brake Rotor: Thickness (Visual Est.)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Brake Pads: Thickness (Visual Est.)", status: "good", notes: "Approx __ mm", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Brake Caliper: Leaks/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Brake Line/Hose: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Suspension: Spring Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Suspension: Shock/Strut Leak", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Suspension: Bushing Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Fuel Door: Alignment/Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Fuel Cap: Seal/Presence", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Brake Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Exterior: Rear Passenger Quarter", name: "Wheel Bearing Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },

        // --- 2.7 Rear End ---
        { category: "Exterior: Rear End", name: "Trunk/Hatch: Operation/Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Trunk/Hatch: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Tail Light (Pass): Operation (Brake/Signal/Running)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Tail Light (Pass): Lens Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Tail Light (Pass): Housing Security", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Tail Light (Driver): Operation (Brake/Signal/Running)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Tail Light (Driver): Lens Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Tail Light (Driver): Housing Security", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Third Brake Light Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Rear Bumper: Condition/Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Rear Bumper: Impact Absorber Area", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Rear Bumper: Sensors/Cameras (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Rear Bumper: Exhaust Cutouts", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "License Plate Area/Light", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Backup Camera Operation (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Rear Emblems/Badges", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Rear Spoiler (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Signs of Rear Impact Damage", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear End", name: "Reverse Lights", status: "good", notes: "", photoUrl: "" },

        // --- 2.8 Rear Driver Quarter ---
        { category: "Exterior: Rear Driver Quarter", name: "Quarter Panel: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Quarter Panel: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Wheel Well Liner", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Wheel: Condition (Scratches, Bends)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Wheel: Lug Nuts/Bolts", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Brand/Model Match", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Size Match (Plaquard)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Tread Depth (Inner/Mid/Outer)", status: "good", notes: "Measure: I__ M__ O__ mm", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Age (DOT Code)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Condition (Cracks, Bulges)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Pressure (Check/Adjust)", status: "good", notes: "PSI: __", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Tire: Wear Pattern", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Brake Rotor: Surface", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Brake Rotor: Thickness (Visual Est.)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Brake Pads: Thickness (Visual Est.)", status: "good", notes: "Approx __ mm", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Brake Caliper: Leaks/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Brake Line/Hose: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Suspension: Spring Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Suspension: Shock/Strut Leak", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Suspension: Bushing Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Brake Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Exterior: Rear Driver Quarter", name: "Wheel Bearing Temp Check (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },

        // --- 2.9 Driver Side ---
        { category: "Exterior: Driver Side", name: "Door Operation (Front/Rear) Handles/Locks", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Rear Door: Panel Alignment (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Rear Door: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Rear Door: Window Trim", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Rear Door: Weatherstripping", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Front Door: Panel Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Front Door: Paint/Damage/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Front Door: Window Trim", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Front Door: Mirror Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Front Door: Weatherstripping", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Rocker Panel/Side Skirt: Alignment", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Rocker Panel/Side Skirt: Damage/Corrosion", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Side Glass: Condition (Chips, Scratches)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "Side Trim Pieces: Secure", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Driver Side", name: "B-Pillar Trim (if applicable)", status: "good", notes: "", photoUrl: "" },

        // --- 2.10 Roof and Glass ---
        { category: "Exterior: Roof and Glass", name: "Windshield: Chips/Cracks", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Windshield: Pitting/Wiper Marks", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Windshield: Seal Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Wipers: Blade Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Washer System Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Roof Panel: Paint/Dents/Rust", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Sunroof: Glass Condition (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Sunroof: Seal Condition (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Sunroof: Drain Check (Visual, if possible)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Sunroof: Operation (Open/Close/Tilt)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Roof Rails/Rack (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Antenna/Shark Fin", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Rear Window: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Rear Window: Defroster Lines", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "Rear Wiper/Washer (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Exterior: Roof and Glass", name: "All Other Glass: Condition", status: "good", notes: "", photoUrl: "" },

        // --- 3. Under Vehicle (Ground-Level Only) ---
        { category: "Under Vehicle (Ground-Level)", name: "Visible Fluid Leaks (Engine, Trans, Diff, PS, Coolant, Brake)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Hanging/Loose Parts (Exhaust, Shields, Wires)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Obvious Rust/Corrosion (Frame, Subframe, Floor Pans)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Exhaust System (Visible Damage/Leaks/Rust)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Exhaust Hangers/Mounts Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Engine Oil Pan Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Transmission Pan/Case Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Driveshaft/CV Axles (Visual)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Suspension Components (Visual Damage/Leaks)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Steering Components (Visual Leaks/Damage)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Brake Lines/Hoses (Visual Condition)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Fuel Tank/Lines (Visual Condition/Leaks)", status: "good", notes: "", photoUrl: "" },
        { category: "Under Vehicle (Ground-Level)", name: "Underbody Covers (Present/Secure/Damage)", status: "good", notes: "", photoUrl: "" },

        // --- 4.1 Driver's Entry Point ---
        { category: "Interior: Driver's Entry", name: "Door Opening Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Handle Feel (Exterior/Interior)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Hinge Condition/Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Door Stop Function", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Weather Stripping Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Sill Plate Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "B-Pillar Trim Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Seat Belt Attachment Point", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "VIN Sticker Verification", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Door Panel Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Door Trim Secure", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Speaker Covers Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Entry", name: "Storage Compartments", status: "good", notes: "", photoUrl: "" },

        // --- 4.2 Driver's Position ---
        { category: "Interior: Driver's Position", name: "Seat: Upholstery Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Seat: Adjustments (Manual/Power)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Seat: Lumbar Support (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Seat: Heating/Cooling (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Seat: Memory Function (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Seat Belt: Condition/Retraction", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Seat Belt: Latch/Buckle Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Steering Wheel: Condition (Wear)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Steering Wheel: Adjustment (Tilt/Telescope)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Steering Wheel: Controls (Audio/Cruise/etc.)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Steering Wheel: Heating (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Horn Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Pedals: Wear/Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Floor Mats/Carpet Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Driver's Position", name: "Dead Pedal Condition", status: "good", notes: "", photoUrl: "" },

        // --- 4.3 Dashboard & Controls ---
        { category: "Interior: Dashboard & Controls", name: "Dashboard Surface Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Instrument Cluster Clarity", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Warning Lights (Key On/Engine Off)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Warning Lights (Engine Running)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Gauge Function (Speedo, Tach, Fuel, Temp)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Odometer Reading Display", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Trip Computer/Info Display", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Headlight Switch Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Wiper/Washer Stalk Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Turn Signal Stalk Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Ignition Switch/Button Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Hazard Light Switch", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Vent Condition/Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Dashboard & Controls", name: "Initial OBD Scan", status: "good", notes: "Codes:__", photoUrl: "" },

        // --- 4.4 Center Console ---
        { category: "Interior: Center Console", name: "Shifter Operation (P-R-N-D)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Shifter: Manual Mode/Paddles (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Shifter: Boot/Trim Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Entertainment System: Power", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Entertainment System: Screen Condition/Touch", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Entertainment System: Button/Knob Function", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Entertainment System: Audio Output (All Speakers)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Entertainment System: Radio/Media Source Test", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Navigation System Operation (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: Button/Knob Function", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: Display Function", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: Mode Selection (Face/Feet/Defrost)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: Fan Speed Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: A/C Cold Output", status: "good", notes: "Temp:__°F/°C", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: Heat Output", status: "good", notes: "Temp:__°F/°C", photoUrl: "" },
        { category: "Interior: Center Console", name: "Climate Controls: Recirculation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Storage Compartments: Operation/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Cup Holders: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "USB/Power Ports: Function", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Emergency Brake: Operation/Hold", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Emergency Brake: Warning Light", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Center Console", name: "Console Trim Condition", status: "good", notes: "", photoUrl: "" },

        // --- 4.5 Passenger Position ---
        { category: "Interior: Passenger Position", name: "Seat: Upholstery Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Seat: Adjustments (Manual/Power)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Seat: Heating/Cooling (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Seat Belt: Condition/Retraction", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Seat Belt: Latch/Buckle Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Airbag Cover Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Airbag Indicators (Passenger On/Off)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Glove Box: Operation/Latch", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Glove Box: Light (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Dashboard Trim Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Door Panel: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Door Handle/Lock Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Window Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Passenger Position", name: "Floor Mats/Carpet Condition", status: "good", notes: "", photoUrl: "" },

        // --- 4.6 Rear Seats - Passenger Side ---
        { category: "Interior: Rear Seats - Passenger", name: "Seat: Upholstery Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Seat: Fold Function (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Seat Belt: Condition/Retraction", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Seat Belt: Latch/Buckle Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Headrest: Condition/Adjustment", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Door Panel: Condition (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Door Handle/Lock Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Window Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Child Lock Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Trim Pieces: Secure/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Floor Mats/Carpet Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Rear Vent Operation (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Passenger", name: "Rear Power Ports (if equipped)", status: "good", notes: "", photoUrl: "" },

        // --- 4.7 Rear Seats - Center ---
        { category: "Interior: Rear Seats - Center", name: "Seat: Upholstery Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Center", name: "Seat Belt: Condition/Retraction", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Center", name: "Seat Belt: Latch/Buckle Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Center", name: "Center Armrest: Operation (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Center", name: "Cup Holders (Rear)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Center", name: "Pass-Through Operation (if equipped)", status: "good", notes: "", photoUrl: "" },

        // --- 4.8 Rear Seats - Driver Side ---
        { category: "Interior: Rear Seats - Driver", name: "Seat: Upholstery Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Seat: Fold Function (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Seat Belt: Condition/Retraction", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Seat Belt: Latch/Buckle Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Headrest: Condition/Adjustment", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Door Panel: Condition (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Door Handle/Lock Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Window Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Child Lock Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Trim Pieces: Secure/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Rear Seats - Driver", name: "Floor Mats/Carpet Condition", status: "good", notes: "", photoUrl: "" },

        // --- 4.9 Headliner & Sunroof ---
        { category: "Interior: Headliner & Sunroof", name: "Headliner: Condition (Stains, Sagging)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Dome/Map Lights Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Grab Handles Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Sun Visors: Condition/Mirrors/Lights", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Sunroof: Operation (Open/Close/Tilt)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Sunroof: Shade Operation (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Sunroof: Seal Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Headliner & Sunroof", name: "Sunroof: Drain Check (Visual)", status: "good", notes: "", photoUrl: "" },

        // --- 4.10 Trunk/Cargo Area ---
        { category: "Interior: Trunk/Cargo Area", name: "Trunk/Hatch Release (Interior/Exterior/Key)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Struts/Hinges Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Trim Panels Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Carpet Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Spare Tire: Presence/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Spare Tire: Pressure", status: "good", notes: "PSI: __", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Jack & Tools: Presence/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Cargo Cover: Operation/Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Cargo Net/Tie-downs (if equipped)", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Water Intrusion Signs", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Trunk Light Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Interior: Trunk/Cargo Area", name: "Emergency Trunk Release", status: "good", notes: "", photoUrl: "" },

        // --- 5. Engine Bay Inspection ---
        { category: "Engine Bay", name: "Hood Release/Latch/Struts", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Under Hood Insulation/Structure", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Engine Oil: Level", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Engine Oil: Condition/Color", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Engine Oil: Cap Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Engine Oil: Filler Neck (Sludge)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Coolant: Level (Reservoir)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Coolant: Condition/Color", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Coolant: Cap Condition/Seal", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Brake Fluid: Level", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Brake Fluid: Condition/Color", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Brake Fluid: Cap Condition/Seal", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Power Steering Fluid: Level (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Power Steering Fluid: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Power Steering Fluid: Cap Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Washer Fluid: Level", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Clutch Fluid: Level/Condition (if applicable)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Serpentine Belt(s): Condition (Cracks, Glazing)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Serpentine Belt(s): Tension", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Timing Belt/Chain Cover Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Hoses (Coolant, PS, Vacuum): Condition (Cracks, Swelling, Leaks)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Hose Clamps: Condition/Tightness", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Battery: Terminals Clean/Tight", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Battery: Hold Down Secure", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Battery: Case Condition (Cracks, Leaks)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Battery: Date Code/Age", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Battery: Load Test Result", status: "good", notes: "Volts:__ CCA:__", photoUrl: "" },
        { category: "Engine Bay", name: "Alternator Charging Output", status: "good", notes: "Volts:__", photoUrl: "" },
        { category: "Engine Bay", name: "Wiring Harnesses: Condition/Routing", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Connectors: Secure/Corrosion", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Ground Straps: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Air Filter: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Air Filter Housing: Secure/Sealed", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Intake Ducts: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Visible Fluid Leaks (Oil, Coolant, PS, Brake, Fuel)", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Engine Mounts: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Transmission Mounts: Condition", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Exhaust Manifold(s): Cracks/Leaks", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Turbocharger (if equipped): Leaks/Shaft Play/Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Supercharger (if equipped): Belt/Noise/Leaks", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Modifications Noted", status: "good", notes: "", photoUrl: "" },
        { category: "Engine Bay", name: "Component Temp Scan: Engine Block (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Engine Bay", name: "Component Temp Scan: Cylinder Heads (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Engine Bay", name: "Component Temp Scan: Cat Converter (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Engine Bay", name: "Component Temp Scan: Alternator (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Engine Bay", name: "Component Temp Scan: AC Compressor (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },
        { category: "Engine Bay", name: "Component Temp Scan: PS Pump (°F/°C)", status: "good", notes: "Temp: __", photoUrl: "" },

        // --- 6. Test Drive Evaluation ---
        { category: "Test Drive", name: "Pre-Drive: Seatbelt Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Pre-Drive: Mirror Adjustment", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Pre-Drive: Warning Lights Check (Key On)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Cold Start: Cranking Speed/Sound", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Cold Start: Time to Start", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Cold Start: Initial Idle RPM/Smoothness", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Cold Start: Exhaust Smoke", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Cold Start: Unusual Noises", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Idle (Warm): RPM/Smoothness", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Idle (Warm): Unusual Noises", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Idle (Warm): Vibrations", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Transmission Engagement (D/R)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Shift Quality (Auto/Manual)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Clutch Operation (Manual)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Steering Effort/Smoothness", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Steering Noise (Lock-to-Lock)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Low Speed Brake Feel/Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Parking Lot: Parking Brake Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Low Speed (0-30 mph): Acceleration Smoothness", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Low Speed (0-30 mph): Engine Response", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Low Speed (0-30 mph): Transmission Shift Points", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Low Speed (0-30 mph): Braking Feel/Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Low Speed (0-30 mph): Suspension Noise (Bumps)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Low Speed (0-30 mph): Steering Feel/Response", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Acceleration (Merging)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Engine Power/Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Transmission Shifts (Up/Down)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Wind Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Road Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Drivetrain Noise/Vibration", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Straight Line Stability", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Steering Feel (On Center)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Lane Change Stability", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Highway (30-70 mph): Cruise Control Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Braking: Normal Braking Feel/Noise", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Braking: Hard Braking Stability/ABS Function", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Braking: Brake Pedal Feel After Use", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: HVAC - A/C Cooling", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: HVAC - Heat Output", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: HVAC - Fan Speeds/Modes", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: Wipers/Washers Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: Turn Signals/Lights Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: Audio System Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: Navigation Operation", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Systems Check: Driver Assist Systems", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Post-Drive: Idle Quality (Warm)", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Post-Drive: Check for Leaks Under Vehicle", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Post-Drive: Brake Temperature Check", status: "good", notes: "LF:__ RF:__ LR:__ RR:__", photoUrl: "" },
        { category: "Test Drive", name: "Post-Drive: Unusual Smells", status: "good", notes: "", photoUrl: "" },
        { category: "Test Drive", name: "Post-Drive: Final Warning Light Check", status: "good", notes: "", photoUrl: "" },

        // --- 7. Final Checks & Diagnostics ---
        { category: "Final Checks & Diagnostics", name: "Final OBD Scan (All Modules)", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "DTCs Present (Document)", status: "good", notes: "Codes:__", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Monitor Readiness Status", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Freeze Frame Data (if DTCs present)", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Live Data Review (Key PIDs if needed)", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Final Fluid Level Check (Oil, Coolant)", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Final Leak Check (Under Vehicle)", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "All Tools/Equipment Removed", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Vehicle Cleaned (Hands/Tools)", status: "good", notes: "", photoUrl: "" },
        { category: "Final Checks & Diagnostics", name: "Review Photos & Voice Notes", status: "good", notes: "", photoUrl: "" },
    ]
};
